name: coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Run tests
        run: |
          mvn test jacoco:report -Djacoco.destFile=exportJacoco/jacoco-fast.exec
      - name: Upload jacoco exec results
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests-jacoco
          path: exportJacoco/jacoco-fast.exec
